using System.Collections.Generic;
using AMath.Core.Assistance;
using AMath.Settings;

namespace AMath.Tutorial.Localization
{
    /// <summary>
    /// Key table for the bootstrap tutorial scene. Language follows
    /// <see cref="GameSettings.LanguageIndex"/> (0 = English, 1 = Thai) so the
    /// tutorial matches the language chosen on the settings screen.
    /// </summary>
    public sealed class TutorialLocalizationProvider : ILocalizedTextProvider
    {
        private readonly Dictionary<string, string> _th;
        private readonly Dictionary<string, string> _en;

        public TutorialLocalizationProvider()
        {
            _th = CreateThaiEntries();
            _en = CreateEnglishEntries();
        }

        /// <inheritdoc />
        public string GetText(string key)
        {
            if (string.IsNullOrWhiteSpace(key))
                return string.Empty;

            Dictionary<string, string> table = GameSettings.LanguageIndex == 1 ? _th : _en;
            return table.TryGetValue(key, out string text) ? text : key;
        }

        private static Dictionary<string, string> CreateThaiEntries()
        {
            return new Dictionary<string, string>
            {
                ["tutorial.intro.title"] = "ยินดีต้อนรับสู่ A-MATH",
                ["tutorial.intro.milestone.orientation"] = "รู้จักพื้นที่เล่น",
                ["tutorial.intro.milestone.equation"] = "วางสมการแรก",
                ["tutorial.intro.milestone.confirm"] = "ยืนยันและดูคู่แข่ง",
                ["tutorial.intro.milestone.complete"] = "สรุปบทพื้นฐาน",
                ["tutorial.intro.step1.objective"] = "ทำความรู้จักหน้าจอฝึกหัด",
                ["tutorial.intro.step1.dialogue"] = "หน้าจอนี้เหมือนห้องแข่งจริง คุณเลือกหมากจากแร็คด้านล่างแล้ววางบนกระดานเอง บทเรียนจะชี้หมากและช่องที่ต้องใช้ทีละจุด",
                ["tutorial.intro.step1.hint"] = "อ่านเป้าหมายด้านบน แล้วกด \"ดำเนินการต่อ\" เมื่อพร้อม",
                ["tutorial.intro.step2.objective"] = "ดูกระดานและแร็คของตัวเอง",
                ["tutorial.intro.step2.dialogue"] = "กระดานอยู่กลางจอ สมการแรกต้องผ่านช่อง ★ ตรงกลาง จึงจะยืนยันการวางได้",
                ["tutorial.intro.step2.hint"] = "กด \"ดำเนินการต่อ\" เมื่อดูกระดานครบแล้ว",
                ["tutorial.intro.step2b.objective"] = "ดูแร็คหมากของคุณ",
                ["tutorial.intro.step2b.dialogue"] = "หมากของคุณอยู่บนแร็คด้านล่าง แตะหมากที่ลูกศรชี้ แล้วแตะช่องบนกระดาน หรือจะลากหมากไปวางก็ได้",
                ["tutorial.intro.step2b.hint"] = "กด \"ดำเนินการต่อ\" เมื่อพร้อมเริ่มวาง",
                ["tutorial.intro.select1.objective"] = "เลือกหมากเลข 1",
                ["tutorial.intro.select1.dialogue"] = "แตะหรือลากหมาก \"1\" จากแร็ค",
                ["tutorial.intro.select1.hint"] = "เลือกหมากที่ไฮไลต์ในแร็ค",
                ["tutorial.intro.place1.objective"] = "วางหมาก 1 บนกระดาน",
                ["tutorial.intro.place1.dialogue"] = "วางหมากลงบนช่องที่ไฮไลต์",
                ["tutorial.intro.place1.hint"] = "คลิกช่องที่สว่าง หรือลากหมากไปวาง",
                ["tutorial.intro.select_plus.objective"] = "เลือกเครื่องหมาย +",
                ["tutorial.intro.select_plus.dialogue"] = "เลือกหมาก \"+\" จากแร็ค",
                ["tutorial.intro.select_plus.hint"] = "แตะหมาก + ในแร็ค",
                ["tutorial.intro.place_plus.objective"] = "วาง + ต่อจาก 1",
                ["tutorial.intro.place_plus.dialogue"] = "วางเครื่องหมาย + บนช่องที่ไฮไลต์",
                ["tutorial.intro.place_plus.hint"] = "วางติดกับหมาก 1",
                ["tutorial.intro.select2.objective"] = "เลือกหมากเลข 2",
                ["tutorial.intro.select2.dialogue"] = "เลือกหมาก \"2\" จากแร็ค",
                ["tutorial.intro.select2.hint"] = "แตะหมาก 2 ในแร็ค",
                ["tutorial.intro.place2.objective"] = "วาง 2 ที่ช่องกลาง ★",
                ["tutorial.intro.place2.dialogue"] = "วางหมาก 2 บนช่องกลาง — สมการแรกต้องครอบ ★",
                ["tutorial.intro.place2.hint"] = "ช่องกลางมีเครื่องหมาย ★",
                ["tutorial.intro.select_equals.objective"] = "เลือกเครื่องหมาย =",
                ["tutorial.intro.select_equals.dialogue"] = "เลือกหมาก \"=\" จากแร็ค",
                ["tutorial.intro.select_equals.hint"] = "แตะหมาก = ในแร็ค",
                ["tutorial.intro.place_equals.objective"] = "วาง = ต่อจาก 2",
                ["tutorial.intro.place_equals.dialogue"] = "วางเครื่องหมาย = บนช่องที่ไฮไลต์",
                ["tutorial.intro.place_equals.hint"] = "ทุกสมการต้องมี =",
                ["tutorial.intro.select3.objective"] = "เลือกหมากเลข 3",
                ["tutorial.intro.select3.dialogue"] = "เลือกหมาก \"3\" จากแร็ค",
                ["tutorial.intro.select3.hint"] = "แตะหมาก 3 ในแร็ค",
                ["tutorial.intro.place3.objective"] = "วาง 3 ปิดสมการ",
                ["tutorial.intro.place3.dialogue"] = "วางหมาก 3 ให้ได้ 1 + 2 = 3",
                ["tutorial.intro.place3.hint"] = "ตรวจว่าสมการถูกต้องก่อนยืนยัน",
                ["tutorial.intro.confirm.objective"] = "ยืนยันการวาง",
                ["tutorial.intro.confirm.dialogue"] = "สมการ 1 + 2 = 3 ครบแล้ว เปิดแถบคำสั่งด้านล่างและกด \"ยืนยัน\" เพื่อลงหมาก",
                ["tutorial.intro.confirm.hint"] = "เปิดคำสั่ง แล้วกดปุ่มยืนยันสีเขียว",
                ["tutorial.intro.step4.objective"] = "ดูบอทวางตามสคริปต์",
                ["tutorial.intro.step4.dialogue"] = "บอทจะต่อจากเลข 2 ที่ช่องกลาง เป็น 2 + 2 = 4 ตามสคริปต์เท่านั้น — ไม่ได้คิดตาเอง",
                ["tutorial.intro.step4.hint"] = "รอสักครู่ บอทจะวางตามบทเรียน",
                ["tutorial.intro.step5.objective"] = "จบบทฝึก",
                ["tutorial.intro.step5.dialogue"] = "เยี่ยมมาก! คุณควบคุมหมากเองได้ แต่ต้องตามสคริปต์ ความคืบหน้าถูกบันทึกแล้ว",
                ["tutorial.chapters.title"] = "เลือกบทฝึกหัด",
                ["tutorial.chapters.subtitle"] = "เรียนทีละจังหวะ เล่นซ้ำได้ และระบบจำจุดที่หยุดไว้ให้",
                ["tutorial.chapters.progress"] = "เรียนจบแล้ว {0}/3 บท",
                ["tutorial.chapters.status_new"] = "พร้อมเริ่มเรียน",
                ["tutorial.chapters.status_progress"] = "กำลังเรียน — ช่วงที่ {0}/{1}",
                ["tutorial.chapters.status_completed"] = "เรียนจบแล้ว",
                ["tutorial.chapters.status_locked"] = "ล็อกอยู่",
                ["tutorial.chapters.intro"] = "บทที่ 1 — พื้นฐาน",
                ["tutorial.chapters.intro_desc"] = "วางสมการแรกผ่านช่องกลาง 1 + 2 = 3",
                ["tutorial.chapters.connect"] = "บทที่ 2 — ต่อสมการ",
                ["tutorial.chapters.connect_desc"] = "ต่อจากสมการที่มีอยู่ด้วย 3 + 4 = 7",
                ["tutorial.chapters.locked"] = "จบบทที่ 1 ก่อนเพื่อปลดล็อก",
                ["tutorial.chapters.completed"] = "เรียนจบแล้ว — เล่นซ้ำได้ทุกเมื่อ",
                ["tutorial.chapters.resume"] = "เรียนต่อจากขั้นที่ {0}",
                ["tutorial.chapters.action_start"] = "เริ่มบทเรียน",
                ["tutorial.chapters.action_continue"] = "เรียนต่อ",
                ["tutorial.chapters.action_replay"] = "เล่นอีกครั้ง",
                ["tutorial.chapters.action_restart"] = "เริ่มใหม่",
                ["tutorial.chapters.action_locked"] = "ยังไม่ปลดล็อก",
                ["tutorial.connect.title"] = "ต่อสมการบนกระดาน",
                ["tutorial.connect.milestone.read"] = "อ่านสมการบนกระดาน",
                ["tutorial.connect.milestone.extend"] = "ต่อสมการเดิม",
                ["tutorial.connect.milestone.confirm"] = "ตรวจและยืนยัน",
                ["tutorial.connect.milestone.complete"] = "สรุปการต่อสมการ",
                ["tutorial.connect.step1.objective"] = "ยินดีต้อนรับสู่บทที่ 2",
                ["tutorial.connect.step1.dialogue"] = "ตาถัดไปต้องใช้หมากใหม่ต่อกับหมากบนกระดาน เราจะต่อจากเลข 3 ให้เป็นสมการที่ถูกต้อง",
                ["tutorial.connect.step1.hint"] = "กด \"ดำเนินการต่อ\" เมื่อพร้อม",
                ["tutorial.connect.step2.objective"] = "ดูสมการที่มีอยู่",
                ["tutorial.connect.step2.dialogue"] = "บนกระดานมี 1 + 2 = 3 อยู่แล้ว ให้วาง + 4 = 7 ต่อจากเลข 3 ลงด้านล่าง เพื่อให้เกิดสมการ 3 + 4 = 7",
                ["tutorial.connect.step2.hint"] = "สังเกตว่าหมากใหม่ต้องติดกับหมากเดิม",
                ["tutorial.connect.select_plus.objective"] = "เลือกเครื่องหมาย +",
                ["tutorial.connect.select_plus.dialogue"] = "เลือกหมาก \"+\" จากแร็ค",
                ["tutorial.connect.select_plus.hint"] = "แตะหมาก + ในแร็ค",
                ["tutorial.connect.place_plus.objective"] = "วาง + ต่อจาก 3",
                ["tutorial.connect.place_plus.dialogue"] = "วาง + ชิดกับเลข 3 บนช่องที่ไฮไลต์",
                ["tutorial.connect.place_plus.hint"] = "หมากใหม่ต้องต่อเนื่องกับหมากบนกระดาน",
                ["tutorial.connect.select4.objective"] = "เลือกหมากเลข 4",
                ["tutorial.connect.select4.dialogue"] = "เลือกหมาก \"4\" จากแร็ค",
                ["tutorial.connect.select4.hint"] = "แตะหมาก 4 ในแร็ค",
                ["tutorial.connect.place4.objective"] = "วาง 4 ต่อจาก +",
                ["tutorial.connect.place4.dialogue"] = "วางหมาก 4 บนช่องที่ไฮไลต์",
                ["tutorial.connect.place4.hint"] = "ต่อเป็น 3 + 4 ...",
                ["tutorial.connect.select_equals.objective"] = "เลือกเครื่องหมาย =",
                ["tutorial.connect.select_equals.dialogue"] = "เลือกหมาก \"=\" จากแร็ค",
                ["tutorial.connect.select_equals.hint"] = "แตะหมาก = ในแร็ค",
                ["tutorial.connect.place_equals.objective"] = "วาง = ต่อจาก 4",
                ["tutorial.connect.place_equals.dialogue"] = "วางเครื่องหมาย = บนช่องที่ไฮไลต์",
                ["tutorial.connect.place_equals.hint"] = "ทุกสมการต้องมี =",
                ["tutorial.connect.select7.objective"] = "เลือกหมากเลข 7",
                ["tutorial.connect.select7.dialogue"] = "เลือกหมาก \"7\" จากแร็ค",
                ["tutorial.connect.select7.hint"] = "แตะหมาก 7 ในแร็ค",
                ["tutorial.connect.place7.objective"] = "วาง 7 ปิดสมการ",
                ["tutorial.connect.place7.dialogue"] = "วาง 7 ให้ได้ 3 + 4 = 7",
                ["tutorial.connect.place7.hint"] = "ตรวจสมการก่อนยืนยัน",
                ["tutorial.connect.confirm.objective"] = "ยืนยันการวาง",
                ["tutorial.connect.confirm.dialogue"] = "ตรวจว่า 3 + 4 = 7 ถูกต้อง แล้วเปิดแถบคำสั่งและกด \"ยืนยัน\"",
                ["tutorial.connect.confirm.hint"] = "เปิดคำสั่ง แล้วกดยืนยัน",
                ["tutorial.connect.complete.objective"] = "จบบทที่ 2",
                ["tutorial.connect.complete.dialogue"] = "เยี่ยม! คุณต่อสมการจากหมากที่มีอยู่ได้แล้ว — นี่คือหัวใจของ A-Math",
                ["tutorial.chapters.premium"] = "บทที่ 3 — พรีเมียม / ผ่าน / สลับ",
                ["tutorial.chapters.premium_desc"] = "ช่องพิเศษ ×2/×3, ผ่านตาเมื่อตัน, สลับหมากจากกอง",
                ["tutorial.chapters.locked_connect"] = "จบบทที่ 2 ก่อนเพื่อปลดล็อก",
                ["tutorial.premium.title"] = "ช่องพรีเมียมและทางออก",
                ["tutorial.premium.milestone.premium"] = "ใช้ช่องพรีเมียม",
                ["tutorial.premium.milestone.pass"] = "ผ่านตาเมื่อตัน",
                ["tutorial.premium.milestone.exchange"] = "สลับหมากจากกอง",
                ["tutorial.premium.milestone.complete"] = "สรุปทางเลือกพิเศษ",
                ["tutorial.premium.step1.objective"] = "ยินดีต้อนรับสู่บทที่ 3",
                ["tutorial.premium.step1.dialogue"] = "บทนี้จะวางหมากบนช่องพรีเมียมเพื่อเพิ่มคะแนน แล้วฝึกใช้คำสั่งผ่านและสลับในแถบคำสั่งด้านล่าง",
                ["tutorial.premium.step1.hint"] = "กด \"ดำเนินการต่อ\" เมื่อพร้อม",
                ["tutorial.premium.premium_intro.objective"] = "ดูช่องพรีเมียม ×2 หมาก",
                ["tutorial.premium.premium_intro.dialogue"] = "ช่องสีส้ม D คือ ×2 หมาก — คราวนี้คุณจะวางเลข 2 ลงบนช่อง D นี้เพื่อคูณคะแนนหมาก ช่อง T คือ ×3 หมาก",
                ["tutorial.premium.premium_intro.hint"] = "สังเกตป้าย ×2 D บนช่องที่ไฮไลต์",
                ["tutorial.premium.select_plus.objective"] = "เลือกเครื่องหมาย +",
                ["tutorial.premium.select_plus.dialogue"] = "ต่อจาก 3 ด้วย + ก่อน — เลือกหมาก \"+\" จากแร็ค",
                ["tutorial.premium.select_plus.hint"] = "แตะหมาก + ในแร็ค",
                ["tutorial.premium.place_plus.objective"] = "วาง + ต่อจาก 3",
                ["tutorial.premium.place_plus.dialogue"] = "วาง + บนช่องที่ไฮไลต์ ติดกับเลข 3",
                ["tutorial.premium.place_plus.hint"] = "วางติดกับเลข 3",
                ["tutorial.premium.select2.objective"] = "เลือกหมากเลข 2",
                ["tutorial.premium.select2.dialogue"] = "ต่อไป วางเลข 2 บนช่อง D — เลือกหมาก \"2\" จากแร็ค",
                ["tutorial.premium.select2.hint"] = "แตะหมาก 2 ในแร็ค",
                ["tutorial.premium.place2.objective"] = "วาง 2 บนช่อง D (×2)",
                ["tutorial.premium.place2.dialogue"] = "วาง 2 ลงบนช่อง D ที่ไฮไลต์ — คะแนนหมากนี้จะถูกคูณสอง!",
                ["tutorial.premium.place2.hint"] = "วางบนช่องสีส้ม ×2 D",
                ["tutorial.premium.select_equals.objective"] = "เลือกเครื่องหมาย =",
                ["tutorial.premium.select_equals.dialogue"] = "เลือกหมาก \"=\" จากแร็ค",
                ["tutorial.premium.select_equals.hint"] = "แตะหมาก = ในแร็ค",
                ["tutorial.premium.place_equals.objective"] = "วาง = ต่อจาก 2",
                ["tutorial.premium.place_equals.dialogue"] = "วางเครื่องหมาย = บนช่องที่ไฮไลต์",
                ["tutorial.premium.place_equals.hint"] = "ทุกสมการต้องมี =",
                ["tutorial.premium.select5.objective"] = "เลือกหมากเลข 5",
                ["tutorial.premium.select5.dialogue"] = "เลือกหมาก \"5\" จากแร็ค",
                ["tutorial.premium.select5.hint"] = "แตะหมาก 5 ในแร็ค",
                ["tutorial.premium.place5.objective"] = "วาง 5 ปิดสมการ",
                ["tutorial.premium.place5.dialogue"] = "วาง 5 ให้ได้ 3 + 2 = 5",
                ["tutorial.premium.place5.hint"] = "ตรวจสมการก่อนยืนยัน",
                ["tutorial.premium.confirm.objective"] = "ยืนยันการวาง",
                ["tutorial.premium.confirm.dialogue"] = "ตรวจว่า 3 + 2 = 5 และหมาก 2 อยู่บนช่อง D แล้วเปิดคำสั่งและกด \"ยืนยัน\"",
                ["tutorial.premium.confirm.hint"] = "เปิดคำสั่ง แล้วกดยืนยัน",
                ["tutorial.premium.pass_intro.objective"] = "เมื่อวางไม่ได้ — ผ่านตา",
                ["tutorial.premium.pass_intro.dialogue"] = "บางครั้งแร็คไม่มีหมากที่ต่อได้ ดูแร็คของคุณ — ไม่มีทางวางที่ถูกกติกา ใช้ \"ผ่าน\" เพื่อข้ามตา (เสียคะแนนเล็กน้อย)",
                ["tutorial.premium.pass_intro.hint"] = "กด \"ดำเนินการต่อ\" เมื่อพร้อม",
                ["tutorial.premium.pass.objective"] = "กดผ่านตา",
                ["tutorial.premium.pass.dialogue"] = "กดเปิดแถบคำสั่งด้านล่าง แล้วกด \"ผ่าน\" เพื่อข้ามตานี้",
                ["tutorial.premium.pass.hint"] = "กดปุ่มผ่านที่ไฮไลต์",
                ["tutorial.premium.exchange_intro.objective"] = "สลับหมากจากกอง",
                ["tutorial.premium.exchange_intro.dialogue"] = "เมื่ออยากเปลี่ยนหมาก ให้เปิดแถบคำสั่งและกด \"สลับ\" เพื่อเข้าโหมดเลือกหมาก กองหมากด้านขวาต้องยังมีหมากอยู่",
                ["tutorial.premium.exchange_intro.hint"] = "กด \"ดำเนินการต่อ\" เมื่อพร้อม",
                ["tutorial.premium.exchange.objective"] = "สลับหมากสองชิ้น",
                ["tutorial.premium.exchange.dialogue"] = "กด \"สลับ\" เพื่อเข้าโหมดเลือก แตะหมาก 13 สองชิ้นที่ลูกศรชี้ แล้วกด \"สลับ\" อีกครั้งเพื่อยืนยัน",
                ["tutorial.premium.exchange.hint"] = "ตามลูกศร: ปุ่มสลับ → หมากชิ้นแรก → ชิ้นที่สอง → ปุ่มสลับ",
                ["tutorial.premium.complete.objective"] = "จบบทที่ 3",
                ["tutorial.premium.complete.dialogue"] = "เยี่ยม! คุณรู้จักช่องพรีเมียม การผ่านตา และการสลับหมากแล้ว — พร้อมเล่นจริง!",
                ["tutorial.ui.title"] = "บทฝึกหัด A-MATH",
                ["tutorial.ui.continue"] = "ดำเนินการต่อ",
                ["tutorial.ui.replay"] = "เริ่มขั้นนี้ใหม่",
                ["tutorial.ui.skip"] = "ข้ามบทฝึก",
                ["tutorial.ui.back_menu"] = "กลับเมนูหลัก",
                ["tutorial.ui.exit_chapter"] = "ออกจากบท",
                ["tutorial.ui.finished"] = "จบบทฝึกแล้ว — เลือกบทถัดไปหรือเล่นซ้ำได้ทันที",
                ["tutorial.ui.skipped"] = "ออกจากบทฝึกแล้ว — ความคืบหน้าถูกเก็บไว้",
                ["tutorial.ui.confirm"] = "ยืนยัน",
                ["tutorial.ui.clear"] = "ล้าง",
                ["tutorial.ui.pass"] = "ผ่าน",
                ["tutorial.ui.exchange"] = "สลับ",
                ["tutorial.ui.menu"] = "เมนู",
                ["tutorial.ui.time"] = "เวลา",
                ["tutorial.ui.no_limit"] = "∞",
                ["tutorial.ui.turn"] = "ตา",
                ["tutorial.ui.score"] = "คะแนน",
                ["tutorial.ui.commands_open"] = "เปิดคำสั่ง",
                ["tutorial.ui.commands_hide"] = "ซ่อนคำสั่ง",
                ["tutorial.ui.idle_hint"] = "เลือกหมากจากแร็คแล้ววางตามช่องที่ชี้",
                ["tutorial.ui.exchange_hint"] = "เลือกหมากที่จะสลับ แล้วกดสลับอีกครั้ง",
                ["tutorial.ui.exchange_arm"] = "เปิดคำสั่ง แล้วกดสลับเพื่อเริ่มเลือกหมาก",
                ["tutorial.ui.exchange_first"] = "เลือกหมาก 13 ชิ้นแรกที่ลูกศรชี้",
                ["tutorial.ui.exchange_second"] = "เลือกหมาก 13 ชิ้นที่สองที่ลูกศรชี้",
                ["tutorial.ui.exchange_commit"] = "กดสลับอีกครั้งเพื่อยืนยัน",
                ["tutorial.ui.pass_turn"] = "วางไม่ได้ — กด \"ผ่าน\" เพื่อข้ามตา",
                ["tutorial.ui.exchange_turn"] = "เปิดคำสั่ง กดสลับ เลือกหมาก แล้วกดสลับอีกครั้ง",
                ["tutorial.ui.your_turn"] = "ตาของคุณ — วางตามช่องที่ไฮไลต์",
                ["tutorial.ui.wait_script"] = "รอสคริปต์ของเกม",
                ["tutorial.ui.you"] = "คุณ",
                ["ui.match.tile_preview_points"] = "เบี้ยนี้ {0} คะแนนเมื่อวางช่องปกติ",
                ["tutorial.ui.bot"] = "บอท",
                ["tutorial.ui.milestone_progress"] = "ช่วง {0} จาก {1}",
                ["tutorial.ui.exit_title"] = "ออกจากบทเรียน?",
                ["tutorial.ui.exit_body"] = "ระบบบันทึก checkpoint ล่าสุดไว้แล้ว คุณกลับมาเรียนต่อได้จากหน้าเลือกบท",
                ["tutorial.ui.exit_confirm"] = "บันทึกและออก",
                ["tutorial.ui.cancel"] = "เรียนต่อ",
                ["tutorial.ui.cancel_action"] = "ยกเลิก",
                ["tutorial.ui.restart_title"] = "เริ่มบทนี้ใหม่?",
                ["tutorial.ui.restart_body"] = "ความคืบหน้าของบทนี้จะกลับไปยังช่วงแรก",
                ["tutorial.ui.restart_confirm"] = "เริ่มใหม่",
                ["tutorial.ui.completion_title"] = "จบบทเรียนแล้ว!",
                ["tutorial.ui.completion_saved"] = "บันทึกความคืบหน้าเรียบร้อย",
                ["tutorial.ui.completion_learned"] = "สิ่งที่คุณทำได้แล้ว",
                ["tutorial.ui.completion_next"] = "เรียนบทถัดไป",
                ["tutorial.ui.completion_replay"] = "ทบทวนอีกครั้ง",
                ["tutorial.ui.completion_picker"] = "เลือกบทอื่น",
                ["tutorial.ui.completion_finish"] = "กลับเมนูเพื่อเล่นจริง",
                ["tutorial.outcome.intro.1"] = "เลือกและวางหมากจากแร็คได้",
                ["tutorial.outcome.intro.2"] = "สร้างสมการแรกผ่านช่องกลางได้",
                ["tutorial.outcome.intro.3"] = "ยืนยันตาและอ่านการเล่นของคู่แข่งได้",
                ["tutorial.outcome.connect.1"] = "อ่านสมการที่อยู่บนกระดานได้",
                ["tutorial.outcome.connect.2"] = "ต่อสมการใหม่เข้ากับหมากเดิมได้",
                ["tutorial.outcome.connect.3"] = "ตรวจความต่อเนื่องก่อนยืนยันได้",
                ["tutorial.outcome.premium.1"] = "ใช้ช่องคูณคะแนนหมากได้",
                ["tutorial.outcome.premium.2"] = "ผ่านตาเมื่อไม่มีทางวางได้",
                ["tutorial.outcome.premium.3"] = "เลือกหมากเพื่อสลับกับกองได้",
                ["tutorial.error.not_your_step"] = "ตอนนี้ยังไม่ถึงตาให้คุณวางตามสคริปต์",
                ["tutorial.error.off_script_cell"] = "วางได้เฉพาะช่องที่ไฮไลต์ตามสคริปต์",
                ["tutorial.error.off_script_tile"] = "ต้องใช้หมากตามสคริปต์สำหรับช่องนี้",
                ["tutorial.error.off_script_confirm"] = "วางให้ครบสมการตามสคริปต์ก่อนยืนยัน",
                ["tutorial.error.pass_disabled"] = "โหมดฝึกหัดห้ามผ่านตา",
                ["tutorial.error.exchange_disabled"] = "โหมดฝึกหัดห้ามสลับหมาก",
                ["tutorial.error.exchange_selection"] = "เลือกหมากที่ไฮไลต์ในแร็คก่อนกดสลับ",
                ["tutorial.error.select_tile_first"] = "เลือกหมากจากแร็คก่อนวางบนกระดาน",
                ["tutorial.error.keep_placed"] = "หมากนี้เป็นส่วนของขั้นที่ทำสำเร็จแล้ว หากต้องการย้อนให้กดเริ่มขั้นนี้ใหม่",
            };
        }

        private static Dictionary<string, string> CreateEnglishEntries()
        {
            return new Dictionary<string, string>
            {
                ["tutorial.intro.title"] = "Welcome to A-MATH",
                ["tutorial.intro.milestone.orientation"] = "Know the play area",
                ["tutorial.intro.milestone.equation"] = "Build the first equation",
                ["tutorial.intro.milestone.confirm"] = "Confirm and watch the opponent",
                ["tutorial.intro.milestone.complete"] = "Review the basics",
                ["tutorial.intro.step1.objective"] = "Get to know the tutorial screen",
                ["tutorial.intro.step1.dialogue"] = "This screen uses the normal match layout. Pick tiles from the rack below and place them yourself. The lesson points to the exact tile and square for each move.",
                ["tutorial.intro.step1.hint"] = "Read the objective above, then press \"Continue\" when ready.",
                ["tutorial.intro.step2.objective"] = "Look at the board and your rack",
                ["tutorial.intro.step2.dialogue"] = "The board is in the centre. Your first equation must cross the centre ★ before you can confirm it.",
                ["tutorial.intro.step2.hint"] = "Press \"Continue\" once you have had a look.",
                ["tutorial.intro.step2b.objective"] = "Look at your tile rack",
                ["tutorial.intro.step2b.dialogue"] = "Your tiles sit in the rack below. Tap the pointed tile and then its board square, or drag the tile onto the square.",
                ["tutorial.intro.step2b.hint"] = "Press \"Continue\" when you are ready to start placing.",
                ["tutorial.intro.select1.objective"] = "Select the number 1 tile",
                ["tutorial.intro.select1.dialogue"] = "Tap or drag the \"1\" tile from your rack.",
                ["tutorial.intro.select1.hint"] = "Pick the highlighted tile in your rack.",
                ["tutorial.intro.place1.objective"] = "Place the 1 on the board",
                ["tutorial.intro.place1.dialogue"] = "Place the tile on the highlighted square.",
                ["tutorial.intro.place1.hint"] = "Click the lit square or drag the tile there.",
                ["tutorial.intro.select_plus.objective"] = "Select the + tile",
                ["tutorial.intro.select_plus.dialogue"] = "Select the \"+\" tile from your rack.",
                ["tutorial.intro.select_plus.hint"] = "Tap the + tile in your rack.",
                ["tutorial.intro.place_plus.objective"] = "Place + after the 1",
                ["tutorial.intro.place_plus.dialogue"] = "Place the + tile on the highlighted square.",
                ["tutorial.intro.place_plus.hint"] = "It should sit right next to the 1.",
                ["tutorial.intro.select2.objective"] = "Select the number 2 tile",
                ["tutorial.intro.select2.dialogue"] = "Select the \"2\" tile from your rack.",
                ["tutorial.intro.select2.hint"] = "Tap the 2 tile in your rack.",
                ["tutorial.intro.place2.objective"] = "Place 2 on the centre ★",
                ["tutorial.intro.place2.dialogue"] = "Place the 2 on the centre square — the first equation must cover ★.",
                ["tutorial.intro.place2.hint"] = "The centre square shows a ★ marker.",
                ["tutorial.intro.select_equals.objective"] = "Select the = tile",
                ["tutorial.intro.select_equals.dialogue"] = "Select the \"=\" tile from your rack.",
                ["tutorial.intro.select_equals.hint"] = "Tap the = tile in your rack.",
                ["tutorial.intro.place_equals.objective"] = "Place = after the 2",
                ["tutorial.intro.place_equals.dialogue"] = "Place the = tile on the highlighted square.",
                ["tutorial.intro.place_equals.hint"] = "Every equation needs an = sign.",
                ["tutorial.intro.select3.objective"] = "Select the number 3 tile",
                ["tutorial.intro.select3.dialogue"] = "Select the \"3\" tile from your rack.",
                ["tutorial.intro.select3.hint"] = "Tap the 3 tile in your rack.",
                ["tutorial.intro.place3.objective"] = "Place 3 to finish the equation",
                ["tutorial.intro.place3.dialogue"] = "Place the 3 so the line reads 1 + 2 = 3.",
                ["tutorial.intro.place3.hint"] = "Check the equation before you confirm.",
                ["tutorial.intro.confirm.objective"] = "Confirm your placement",
                ["tutorial.intro.confirm.dialogue"] = "The equation 1 + 2 = 3 is complete. Open the command drawer below and press \"Confirm\" to play it.",
                ["tutorial.intro.confirm.hint"] = "Open commands, then press the green Confirm button.",
                ["tutorial.intro.step4.objective"] = "Watch the bot follow the script",
                ["tutorial.intro.step4.dialogue"] = "The bot extends the centre 2 into 2 + 2 = 4. It only plays the authored move — it does not search for one.",
                ["tutorial.intro.step4.hint"] = "Wait a moment — the bot will play the scripted line.",
                ["tutorial.intro.step5.objective"] = "Finish the tutorial",
                ["tutorial.intro.step5.dialogue"] = "Great job! You controlled your own tiles, but only along the script. Progress is saved.",
                ["tutorial.chapters.title"] = "Choose a Chapter",
                ["tutorial.chapters.subtitle"] = "Learn at your pace, replay freely, and continue where you left off",
                ["tutorial.chapters.progress"] = "Completed {0}/3 chapters",
                ["tutorial.chapters.status_new"] = "Ready to start",
                ["tutorial.chapters.status_progress"] = "In progress — milestone {0}/{1}",
                ["tutorial.chapters.status_completed"] = "Completed",
                ["tutorial.chapters.status_locked"] = "Locked",
                ["tutorial.chapters.intro"] = "Chapter 1 — Basics",
                ["tutorial.chapters.intro_desc"] = "Place your first equation through the centre: 1 + 2 = 3",
                ["tutorial.chapters.connect"] = "Chapter 2 — Connect",
                ["tutorial.chapters.connect_desc"] = "Extend the existing line with 3 + 4 = 7",
                ["tutorial.chapters.locked"] = "Complete Chapter 1 to unlock",
                ["tutorial.chapters.completed"] = "Completed — replay whenever you like",
                ["tutorial.chapters.resume"] = "Continue from step {0}",
                ["tutorial.chapters.action_start"] = "Start Chapter",
                ["tutorial.chapters.action_continue"] = "Continue",
                ["tutorial.chapters.action_replay"] = "Replay",
                ["tutorial.chapters.action_restart"] = "Start Over",
                ["tutorial.chapters.action_locked"] = "Locked",
                ["tutorial.connect.title"] = "Connect on the Board",
                ["tutorial.connect.milestone.read"] = "Read the board equation",
                ["tutorial.connect.milestone.extend"] = "Extend the existing equation",
                ["tutorial.connect.milestone.confirm"] = "Check and confirm",
                ["tutorial.connect.milestone.complete"] = "Review connected equations",
                ["tutorial.connect.step1.objective"] = "Welcome to Chapter 2",
                ["tutorial.connect.step1.dialogue"] = "A new move must connect to tiles already on the board. You will extend from the 3 to form another valid equation.",
                ["tutorial.connect.step1.hint"] = "Press \"Continue\" when ready.",
                ["tutorial.connect.step2.objective"] = "Study the existing equation",
                ["tutorial.connect.step2.dialogue"] = "The board already shows 1 + 2 = 3. Place + 4 = 7 below the 3 to form 3 + 4 = 7.",
                ["tutorial.connect.step2.hint"] = "New tiles must touch existing ones.",
                ["tutorial.connect.select_plus.objective"] = "Select the + tile",
                ["tutorial.connect.select_plus.dialogue"] = "Select the \"+\" tile from your rack.",
                ["tutorial.connect.select_plus.hint"] = "Tap the + tile in your rack.",
                ["tutorial.connect.place_plus.objective"] = "Place + after the 3",
                ["tutorial.connect.place_plus.dialogue"] = "Place + next to the 3 on the highlighted square.",
                ["tutorial.connect.place_plus.hint"] = "Extensions must connect to the board.",
                ["tutorial.connect.select4.objective"] = "Select the 4 tile",
                ["tutorial.connect.select4.dialogue"] = "Select the \"4\" tile from your rack.",
                ["tutorial.connect.select4.hint"] = "Tap the 4 tile in your rack.",
                ["tutorial.connect.place4.objective"] = "Place 4 after +",
                ["tutorial.connect.place4.dialogue"] = "Place the 4 on the highlighted square.",
                ["tutorial.connect.place4.hint"] = "You are building 3 + 4 ...",
                ["tutorial.connect.select_equals.objective"] = "Select the = tile",
                ["tutorial.connect.select_equals.dialogue"] = "Select the \"=\" tile from your rack.",
                ["tutorial.connect.select_equals.hint"] = "Tap the = tile in your rack.",
                ["tutorial.connect.place_equals.objective"] = "Place = after 4",
                ["tutorial.connect.place_equals.dialogue"] = "Place = on the highlighted square.",
                ["tutorial.connect.place_equals.hint"] = "Every equation needs =.",
                ["tutorial.connect.select7.objective"] = "Select the 7 tile",
                ["tutorial.connect.select7.dialogue"] = "Select the \"7\" tile from your rack.",
                ["tutorial.connect.select7.hint"] = "Tap the 7 tile in your rack.",
                ["tutorial.connect.place7.objective"] = "Place 7 to finish",
                ["tutorial.connect.place7.dialogue"] = "Place 7 so the line reads 3 + 4 = 7.",
                ["tutorial.connect.place7.hint"] = "Check the equation, then confirm.",
                ["tutorial.connect.confirm.objective"] = "Confirm your placement",
                ["tutorial.connect.confirm.dialogue"] = "Check that 3 + 4 = 7 is correct, then open commands and press \"Confirm\".",
                ["tutorial.connect.confirm.hint"] = "Open commands, then press Confirm.",
                ["tutorial.connect.complete.objective"] = "Chapter 2 complete",
                ["tutorial.connect.complete.dialogue"] = "Great! You connected to existing tiles — the core skill of A-Math.",
                ["tutorial.chapters.premium"] = "Chapter 3 — Premium / Pass / Exchange",
                ["tutorial.chapters.premium_desc"] = "Premium squares, passing when stuck, and exchanging tiles",
                ["tutorial.chapters.locked_connect"] = "Complete Chapter 2 to unlock",
                ["tutorial.premium.title"] = "Premium Squares and Options",
                ["tutorial.premium.milestone.premium"] = "Use a premium square",
                ["tutorial.premium.milestone.pass"] = "Pass when stuck",
                ["tutorial.premium.milestone.exchange"] = "Exchange tiles",
                ["tutorial.premium.milestone.complete"] = "Review special options",
                ["tutorial.premium.step1.objective"] = "Welcome to Chapter 3",
                ["tutorial.premium.step1.dialogue"] = "This chapter uses a premium square to raise your score, then teaches Pass and Exchange in the command drawer below.",
                ["tutorial.premium.step1.hint"] = "Press \"Continue\" when ready.",
                ["tutorial.premium.premium_intro.objective"] = "Study the ×2 tile premium",
                ["tutorial.premium.premium_intro.dialogue"] = "Orange D squares are ×2 tile — this time you will place the 2 on this D square to double its points. T squares are ×3 tile.",
                ["tutorial.premium.premium_intro.hint"] = "Look for the ×2 D label on the highlighted square.",
                ["tutorial.premium.select_plus.objective"] = "Select the + tile",
                ["tutorial.premium.select_plus.dialogue"] = "First extend from the 3 with + — select \"+\" from your rack.",
                ["tutorial.premium.select_plus.hint"] = "Tap the + tile in your rack.",
                ["tutorial.premium.place_plus.objective"] = "Place + after the 3",
                ["tutorial.premium.place_plus.dialogue"] = "Place + on the highlighted square next to the 3.",
                ["tutorial.premium.place_plus.hint"] = "Connect to the 3.",
                ["tutorial.premium.select2.objective"] = "Select the 2 tile",
                ["tutorial.premium.select2.dialogue"] = "Next, place the 2 on the D square — select the \"2\" tile from your rack.",
                ["tutorial.premium.select2.hint"] = "Tap the 2 tile in your rack.",
                ["tutorial.premium.place2.objective"] = "Place 2 on the D (×2) square",
                ["tutorial.premium.place2.dialogue"] = "Place 2 on the highlighted D square — this tile's score will double!",
                ["tutorial.premium.place2.hint"] = "Land on the orange ×2 D cell.",
                ["tutorial.premium.select_equals.objective"] = "Select the = tile",
                ["tutorial.premium.select_equals.dialogue"] = "Select the \"=\" tile from your rack.",
                ["tutorial.premium.select_equals.hint"] = "Tap the = tile in your rack.",
                ["tutorial.premium.place_equals.objective"] = "Place = after 2",
                ["tutorial.premium.place_equals.dialogue"] = "Place = on the highlighted square.",
                ["tutorial.premium.place_equals.hint"] = "Every equation needs =.",
                ["tutorial.premium.select5.objective"] = "Select the 5 tile",
                ["tutorial.premium.select5.dialogue"] = "Select the \"5\" tile from your rack.",
                ["tutorial.premium.select5.hint"] = "Tap the 5 tile in your rack.",
                ["tutorial.premium.place5.objective"] = "Place 5 to finish",
                ["tutorial.premium.place5.dialogue"] = "Place 5 so the line reads 3 + 2 = 5.",
                ["tutorial.premium.place5.hint"] = "Check the equation, then confirm.",
                ["tutorial.premium.confirm.objective"] = "Confirm your placement",
                ["tutorial.premium.confirm.dialogue"] = "Check that 3 + 2 = 5 and the 2 is on D, then open commands and press \"Confirm\".",
                ["tutorial.premium.confirm.hint"] = "Open commands, then press Confirm.",
                ["tutorial.premium.pass_intro.objective"] = "When stuck — pass",
                ["tutorial.premium.pass_intro.dialogue"] = "Sometimes your rack cannot form a legal move. Look at your rack — nothing connects. Use \"Pass\" to skip your turn (with a small penalty).",
                ["tutorial.premium.pass_intro.hint"] = "Press \"Continue\" when ready.",
                ["tutorial.premium.pass.objective"] = "Press Pass",
                ["tutorial.premium.pass.dialogue"] = "Open the command drawer below, then press \"Pass\" to skip this turn.",
                ["tutorial.premium.pass.hint"] = "Press the highlighted Pass button.",
                ["tutorial.premium.exchange_intro.objective"] = "Exchange from the pool",
                ["tutorial.premium.exchange_intro.dialogue"] = "To replace tiles, open the command drawer and press \"Exchange\" to enter selection mode. The bag on the right must contain tiles.",
                ["tutorial.premium.exchange_intro.hint"] = "Press \"Continue\" when ready.",
                ["tutorial.premium.exchange.objective"] = "Exchange two tiles",
                ["tutorial.premium.exchange.dialogue"] = "Press \"Exchange\" to select tiles. Tap the two pointed 13 tiles, then press \"Exchange\" again to confirm.",
                ["tutorial.premium.exchange.hint"] = "Follow the pointer: Exchange → first tile → second tile → Exchange.",
                ["tutorial.premium.complete.objective"] = "Chapter 3 complete",
                ["tutorial.premium.complete.dialogue"] = "Great! You know premium squares, passing, and exchanging — ready for real matches!",
                ["tutorial.ui.title"] = "A-MATH Tutorial",
                ["tutorial.ui.continue"] = "Continue",
                ["tutorial.ui.replay"] = "Restart This Step",
                ["tutorial.ui.skip"] = "Skip Tutorial",
                ["tutorial.ui.back_menu"] = "Back to Menu",
                ["tutorial.ui.exit_chapter"] = "Exit Chapter",
                ["tutorial.ui.finished"] = "Tutorial complete — choose the next chapter or replay this one.",
                ["tutorial.ui.skipped"] = "Tutorial closed — your progress has been saved.",
                ["tutorial.ui.confirm"] = "Confirm",
                ["tutorial.ui.clear"] = "Clear",
                ["tutorial.ui.pass"] = "Pass",
                ["tutorial.ui.exchange"] = "Exchange",
                ["tutorial.ui.menu"] = "Menu",
                ["tutorial.ui.time"] = "Time",
                ["tutorial.ui.no_limit"] = "∞",
                ["tutorial.ui.turn"] = "Turn",
                ["tutorial.ui.score"] = "Score",
                ["tutorial.ui.commands_open"] = "Commands",
                ["tutorial.ui.commands_hide"] = "Hide",
                ["tutorial.ui.idle_hint"] = "Choose a rack tile and place it on the pointed square",
                ["tutorial.ui.exchange_hint"] = "Select tiles to exchange, then press Exchange again",
                ["tutorial.ui.exchange_arm"] = "Open commands and press Exchange to start selecting tiles",
                ["tutorial.ui.exchange_first"] = "Select the first pointed 13 tile",
                ["tutorial.ui.exchange_second"] = "Select the second pointed 13 tile",
                ["tutorial.ui.exchange_commit"] = "Press Exchange again to confirm",
                ["tutorial.ui.pass_turn"] = "No legal move — press \"Pass\" to skip",
                ["tutorial.ui.exchange_turn"] = "Open commands, press Exchange, select tiles, then press Exchange again",
                ["tutorial.ui.your_turn"] = "Your turn — place on the highlighted cells",
                ["tutorial.ui.wait_script"] = "Waiting for the scripted turn",
                ["tutorial.ui.you"] = "you",
                ["ui.match.tile_preview_points"] = "This tile scores {0} points on a normal square",
                ["tutorial.ui.bot"] = "bot",
                ["tutorial.ui.milestone_progress"] = "Milestone {0} of {1}",
                ["tutorial.ui.exit_title"] = "Leave this lesson?",
                ["tutorial.ui.exit_body"] = "Your latest checkpoint is saved. You can continue from the chapter screen later.",
                ["tutorial.ui.exit_confirm"] = "Save and Leave",
                ["tutorial.ui.cancel"] = "Keep Learning",
                ["tutorial.ui.cancel_action"] = "Cancel",
                ["tutorial.ui.restart_title"] = "Start this chapter over?",
                ["tutorial.ui.restart_body"] = "This chapter's progress will return to its first milestone.",
                ["tutorial.ui.restart_confirm"] = "Start Over",
                ["tutorial.ui.completion_title"] = "Lesson Complete!",
                ["tutorial.ui.completion_saved"] = "Progress saved",
                ["tutorial.ui.completion_learned"] = "You can now",
                ["tutorial.ui.completion_next"] = "Learn the Next Chapter",
                ["tutorial.ui.completion_replay"] = "Review Again",
                ["tutorial.ui.completion_picker"] = "Choose Another Chapter",
                ["tutorial.ui.completion_finish"] = "Back to Menu and Play",
                ["tutorial.outcome.intro.1"] = "Select and place tiles from your rack",
                ["tutorial.outcome.intro.2"] = "Build the first equation through the centre",
                ["tutorial.outcome.intro.3"] = "Confirm a turn and read the opponent's move",
                ["tutorial.outcome.connect.1"] = "Read an equation already on the board",
                ["tutorial.outcome.connect.2"] = "Connect a new equation to existing tiles",
                ["tutorial.outcome.connect.3"] = "Check continuity before confirming",
                ["tutorial.outcome.premium.1"] = "Use a tile-score premium square",
                ["tutorial.outcome.premium.2"] = "Pass when no legal move is available",
                ["tutorial.outcome.premium.3"] = "Select tiles to exchange with the pool",
                ["tutorial.error.not_your_step"] = "It is not your scripted turn yet.",
                ["tutorial.error.off_script_cell"] = "Place only on the highlighted scripted cells.",
                ["tutorial.error.off_script_tile"] = "Use the scripted tile for that square.",
                ["tutorial.error.off_script_confirm"] = "Finish the scripted equation before confirming.",
                ["tutorial.error.pass_disabled"] = "Passing is disabled in the tutorial.",
                ["tutorial.error.exchange_disabled"] = "Exchanging is disabled in the tutorial.",
                ["tutorial.error.exchange_selection"] = "Select the highlighted rack tiles before exchanging.",
                ["tutorial.error.select_tile_first"] = "Select a tile from your rack before placing on the board.",
                ["tutorial.error.keep_placed"] = "That tile belongs to a completed step. Use Restart This Step if you need to go back.",
            };
        }
    }
}
